# Generated by Django 4.2.6 on 2023-10-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0003_alter_article_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article', 'Article'), ('comment', 'Comment')], default='article', max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentlikenotification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='articlecommentnotification',
            name='new_comment',
        ),
        migrations.AddField(
            model_name='articlecommentnotification',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replycommentnotification',
            name='new_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
        migrations.AlterField(
            model_name='replycommentnotification',
            name='source_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='api.comment'),
        ),
        migrations.DeleteModel(
            name='ArticleLikeNotification',
        ),
        migrations.DeleteModel(
            name='CommentLikeNotification',
        ),
    ]
